services:
  mongo_db:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  spring_backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    container_name: spring_backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo_db:27017/testdb?authSource=admin
    depends_on:
      - mongo_db

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo_db
    depends_on:
      - mongo_db

volumes:
  mongo_data:

